var data = [
    {
        "oil": "almond",
        "type": "refined",
        "taste": "2",
        "cost": "7.59",
        "sat": "8",
        "poly": "17",
        "mono": "70",
        "other": "5",
        "total": "100",
        "nonfat": "0",
        "ratio": "",
        "omega3": "0",
        "omega6": "17",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "230",
        "smokeF": "446"
    },
    {
        "oil": "beeftallow",
        "type": "",
        "taste": "1",
        "cost": "0.95",
        "sat": "50",
        "poly": "4",
        "mono": "42",
        "other": "4",
        "total": "100",
        "nonfat": "0",
        "ratio": "5",
        "omega3": "1",
        "omega6": "3",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "220",
        "smokeF": "428"
    },
    {
        "oil": "flaxseed",
        "type": "",
        "taste": "2",
        "cost": "3.66",
        "sat": "9",
        "poly": "66",
        "mono": "20",
        "other": "4",
        "total": "100",
        "nonfat": "0",
        "ratio": "0.21",
        "omega3": "59",
        "omega6": "13",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "107",
        "smokeF": "225"
    },
    {
        "oil": "apricotkernel",
        "type": "",
        "taste": "0",
        "cost": "8.45",
        "sat": "6",
        "poly": "29",
        "mono": "60",
        "other": "4",
        "total": "100",
        "nonfat": "0",
        "ratio": "",
        "omega3": "0",
        "omega6": "29",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "257",
        "smokeF": "495"
    },
    {
        "oil": "argan",
        "type": "",
        "taste": "2",
        "cost": "17.48",
        "sat": "18",
        "poly": "37",
        "mono": "43",
        "other": "2",
        "total": "100",
        "nonfat": "0",
        "ratio": "18",
        "omega3": "2",
        "omega6": "35",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "218",
        "smokeF": "424"
    },
    {
        "oil": "avocado",
        "type": "refined",
        "taste": "1",
        "cost": "2.75",
        "sat": "12",
        "poly": "14",
        "mono": "70",
        "other": "4",
        "total": "100",
        "nonfat": "0",
        "ratio": "13",
        "omega3": "1",
        "omega6": "13",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "269",
        "smokeF": "517"
    },
    {
        "oil": "brazilnut",
        "type": "",
        "taste": "2",
        "cost": "3.10",
        "sat": "25",
        "poly": "36",
        "mono": "39",
        "other": "0",
        "total": "100",
        "nonfat": "0",
        "ratio": "",
        "omega3": "0",
        "omega6": "36",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "195",
        "smokeF": "408"
    },
    {
        "oil": "butter",
        "type": "",
        "taste": "2",
        "cost": "0.90",
        "sat": "51",
        "poly": "3",
        "mono": "21",
        "other": "6",
        "total": "81",
        "nonfat": "19",
        "ratio": "9",
        "omega3": "0",
        "omega6": "3",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "167",
        "smokeF": "333"
    },
    {
        "oil": "butter,clarified(ghee)",
        "type": "",
        "taste": "2",
        "cost": "2.26",
        "sat": "65",
        "poly": "3",
        "mono": "32",
        "other": "0",
        "total": "100",
        "nonfat": "0",
        "ratio": "",
        "omega3": "0",
        "omega6": "3",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "235",
        "smokeF": "455"
    },
    {
        "oil": "canola/rapeseed",
        "type": "refined",
        "taste": "0",
        "cost": "0.56",
        "sat": "8",
        "poly": "26",
        "mono": "61",
        "other": "5",
        "total": "100",
        "nonfat": "0",
        "ratio": "2",
        "omega3": "8",
        "omega6": "19",
        "transfat": "1.80",
        "fridge": "n",
        "smokeC": "207",
        "smokeF": "404"
    },
    {
        "oil": "cashew",
        "type": "",
        "taste": "1",
        "cost": "14.00",
        "sat": "11",
        "poly": "8",
        "mono": "73",
        "other": "8",
        "total": "100",
        "nonfat": "0",
        "ratio": "",
        "omega3": "0",
        "omega6": "8",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "149",
        "smokeF": "300"
    },
    {
        "oil": "coconut",
        "type": "unrefined",
        "taste": "2",
        "cost": "1.29",
        "sat": "87",
        "poly": "2",
        "mono": "6",
        "other": "6",
        "total": "100",
        "nonfat": "0",
        "ratio": "",
        "omega3": "0",
        "omega6": "2",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "179",
        "smokeF": "353"
    },
    {
        "oil": "coconut",
        "type": "refined",
        "taste": "0",
        "cost": "3.03",
        "sat": "87",
        "poly": "2",
        "mono": "6",
        "other": "6",
        "total": "100",
        "nonfat": "0",
        "ratio": "",
        "omega3": "0",
        "omega6": "2",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "235",
        "smokeF": "455"
    },
    {
        "oil": "corn",
        "type": "refined",
        "taste": "0",
        "cost": "0.29",
        "sat": "13",
        "poly": "59",
        "mono": "24",
        "other": "4",
        "total": "100",
        "nonfat": "0",
        "ratio": "46",
        "omega3": "1",
        "omega6": "54",
        "transfat": "0.50",
        "fridge": "n",
        "smokeC": "233",
        "smokeF": "451"
    },
    {
        "oil": "cottonseed",
        "type": "",
        "taste": "1",
        "cost": "0.32",
        "sat": "26",
        "poly": "52",
        "mono": "18",
        "other": "4",
        "total": "100",
        "nonfat": "0",
        "ratio": "258",
        "omega3": "0",
        "omega6": "52",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "216",
        "smokeF": "420"
    },
    {
        "oil": "duckfat",
        "type": "",
        "taste": "2",
        "cost": "5.40",
        "sat": "33",
        "poly": "13",
        "mono": "49",
        "other": "5",
        "total": "100",
        "nonfat": "0",
        "ratio": "12",
        "omega3": "1",
        "omega6": "12",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "190",
        "smokeF": "374"
    },
    {
        "oil": "fish",
        "type": "cod liver",
        "taste": "1",
        "cost": "16.94",
        "sat": "23",
        "poly": "23",
        "mono": "47",
        "other": "8",
        "total": "100",
        "nonfat": "0",
        "ratio": "0.05",
        "omega3": "20",
        "omega6": "1",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "113",
        "smokeF": "235"
    },
    {
        "oil": "grapeseed",
        "type": "unrefined",
        "taste": "0",
        "cost": "0.79",
        "sat": "10",
        "poly": "70",
        "mono": "16",
        "other": "4",
        "total": "100",
        "nonfat": "0",
        "ratio": "696",
        "omega3": "0",
        "omega6": "70",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "221",
        "smokeF": "430"
    },
    {
        "oil": "hazelnut",
        "type": "unrefined",
        "taste": "2",
        "cost": "2.58",
        "sat": "7",
        "poly": "10",
        "mono": "78",
        "other": "4",
        "total": "100",
        "nonfat": "0",
        "ratio": "",
        "omega3": "0",
        "omega6": "10",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "221",
        "smokeF": "429"
    },
    {
        "oil": "hemp",
        "type": "",
        "taste": "1",
        "cost": "3.94",
        "sat": "8",
        "poly": "80",
        "mono": "12",
        "other": "0",
        "total": "100",
        "nonfat": "0",
        "ratio": "2",
        "omega3": "25",
        "omega6": "55",
        "transfat": "0",
        "fridge": "y",
        "smokeC": "165",
        "smokeF": "329"
    },
    {
        "oil": "lard",
        "type": "",
        "taste": "0",
        "cost": "0.50",
        "sat": "39",
        "poly": "11",
        "mono": "45",
        "other": "4",
        "total": "100",
        "nonfat": "0",
        "ratio": "10",
        "omega3": "1",
        "omega6": "10",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "183",
        "smokeF": "361"
    },
    {
        "oil": "macadamia",
        "type": "",
        "taste": "2",
        "cost": "6.80",
        "sat": "15",
        "poly": "2",
        "mono": "79",
        "other": "4",
        "total": "100",
        "nonfat": "0",
        "ratio": "",
        "omega3": "0",
        "omega6": "2",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "203",
        "smokeF": "397"
    },
    {
        "oil": "margarine",
        "type": "hard",
        "taste": "1",
        "cost": "0.44",
        "sat": "17",
        "poly": "21",
        "mono": "39",
        "other": "4",
        "total": "81",
        "nonfat": "19",
        "ratio": "13",
        "omega3": "2",
        "omega6": "19",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "155",
        "smokeF": "311"
    },
    {
        "oil": "margarine",
        "type": "soft",
        "taste": "1",
        "cost": "0.64",
        "sat": "12",
        "poly": "21",
        "mono": "45",
        "other": "2",
        "total": "80",
        "nonfat": "20",
        "ratio": "2",
        "omega3": "6",
        "omega6": "15",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "158",
        "smokeF": "316"
    },
    {
        "oil": "mustard",
        "type": "",
        "taste": "2",
        "cost": "1.02",
        "sat": "12",
        "poly": "21",
        "mono": "59",
        "other": "8",
        "total": "100",
        "nonfat": "0",
        "ratio": "3",
        "omega3": "6",
        "omega6": "15",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "232",
        "smokeF": "450"
    },
    {
        "oil": "olive",
        "type": "extra virgin",
        "taste": "2",
        "cost": "1.09",
        "sat": "14",
        "poly": "11",
        "mono": "73",
        "other": "2",
        "total": "100",
        "nonfat": "0",
        "ratio": "13",
        "omega3": "1",
        "omega6": "10",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "160",
        "smokeF": "320"
    },
    {
        "oil": "olive",
        "type": "virgin",
        "taste": "1",
        "cost": "1.15",
        "sat": "16",
        "poly": "14",
        "mono": "70",
        "other": "0",
        "total": "100",
        "nonfat": "0",
        "ratio": "13",
        "omega3": "1",
        "omega6": "10",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "214",
        "smokeF": "417"
    },
    {
        "oil": "olive",
        "type": "refined",
        "taste": "0",
        "cost": "1.09",
        "sat": "14",
        "poly": "11",
        "mono": "34",
        "other": "41",
        "total": "100",
        "nonfat": "0",
        "ratio": "13",
        "omega3": "1",
        "omega6": "10",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "241",
        "smokeF": "466"
    },
    {
        "oil": "palm",
        "type": "defractionated",
        "taste": "1",
        "cost": "0.75",
        "sat": "49",
        "poly": "9",
        "mono": "37",
        "other": "4",
        "total": "100",
        "nonfat": "0",
        "ratio": "46",
        "omega3": "0",
        "omega6": "9",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "226",
        "smokeF": "438"
    },
    {
        "oil": "peanut",
        "type": "refined",
        "taste": "0",
        "cost": "0.72",
        "sat": "17",
        "poly": "32",
        "mono": "46",
        "other": "5",
        "total": "100",
        "nonfat": "0",
        "ratio": "",
        "omega3": "0",
        "omega6": "32",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "233",
        "smokeF": "451"
    },
    {
        "oil": "pecannut",
        "type": "",
        "taste": "0",
        "cost": "11.20",
        "sat": "8",
        "poly": "25",
        "mono": "62",
        "other": "5",
        "total": "100",
        "nonfat": "0",
        "ratio": "",
        "omega3": "0",
        "omega6": "25",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "232",
        "smokeF": "450"
    },
    {
        "oil": "pumpkinseed",
        "type": "",
        "taste": "2",
        "cost": "4.45",
        "sat": "9",
        "poly": "57",
        "mono": "34",
        "other": "0",
        "total": "100",
        "nonfat": "0",
        "ratio": "",
        "omega3": "0",
        "omega6": "57",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "107",
        "smokeF": "225"
    },
    {
        "oil": "ricebran",
        "type": "",
        "taste": "0",
        "cost": "0.64",
        "sat": "9",
        "poly": "33",
        "mono": "47",
        "other": "11",
        "total": "100",
        "nonfat": "0",
        "ratio": "21",
        "omega3": "2",
        "omega6": "33",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "254",
        "smokeF": "490"
    },
    {
        "oil": "safflower",
        "type": "high oleic",
        "taste": "1",
        "cost": "1.60",
        "sat": "6",
        "poly": "14",
        "mono": "75",
        "other": "5",
        "total": "100",
        "nonfat": "0",
        "ratio": "",
        "omega3": "0",
        "omega6": "14",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "229",
        "smokeF": "445"
    },
    {
        "oil": "sesame",
        "type": "unrefined",
        "taste": "2",
        "cost": "1.29",
        "sat": "14",
        "poly": "43",
        "mono": "43",
        "other": "0",
        "total": "100",
        "nonfat": "0",
        "ratio": "",
        "omega3": "0",
        "omega6": "43",
        "transfat": "0",
        "fridge": "y",
        "smokeC": "177",
        "smokeF": "350"
    },
    {
        "oil": "sesame",
        "type": "semi-refined",
        "taste": "0",
        "cost": "0.00",
        "sat": "14",
        "poly": "42",
        "mono": "40",
        "other": "4",
        "total": "100",
        "nonfat": "0",
        "ratio": "138",
        "omega3": "0",
        "omega6": "41",
        "transfat": "0",
        "fridge": "y",
        "smokeC": "232",
        "smokeF": "450"
    },
    {
        "oil": "soybean",
        "type": "refined",
        "taste": "0",
        "cost": "2.41",
        "sat": "15",
        "poly": "38",
        "mono": "43",
        "other": "4",
        "total": "100",
        "nonfat": "0",
        "ratio": "13",
        "omega3": "3",
        "omega6": "35",
        "transfat": "0.50",
        "fridge": "n",
        "smokeC": "233",
        "smokeF": "451"
    },
    {
        "oil": "suet",
        "type": "",
        "taste": "1",
        "cost": "0.54",
        "sat": "52",
        "poly": "3",
        "mono": "32",
        "other": "7",
        "total": "94",
        "nonfat": "6",
        "ratio": "3",
        "omega3": "1",
        "omega6": "2",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "200",
        "smokeF": "392"
    },
    {
        "oil": "sunflower",
        "type": "linoleic",
        "taste": "2",
        "cost": "0.25",
        "sat": "13",
        "poly": "36",
        "mono": "46",
        "other": "4",
        "total": "100",
        "nonfat": "0",
        "ratio": "39",
        "omega3": "1",
        "omega6": "35",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "236",
        "smokeF": "458"
    },
    {
        "oil": "sunflower",
        "type": "high-oleic",
        "taste": "0",
        "cost": "1.17",
        "sat": "10",
        "poly": "4",
        "mono": "84",
        "other": "3",
        "total": "100",
        "nonfat": "0",
        "ratio": "19",
        "omega3": "0",
        "omega6": "4",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "233",
        "smokeF": "451"
    },
    {
        "oil": "walnut",
        "type": "unrefined",
        "taste": "2",
        "cost": "1.00",
        "sat": "9",
        "poly": "63",
        "mono": "23",
        "other": "5",
        "total": "100",
        "nonfat": "0",
        "ratio": "5",
        "omega3": "10",
        "omega6": "53",
        "transfat": "0",
        "fridge": "n",
        "smokeC": "160",
        "smokeF": "320"
    },
    {
        "oil": "wheatgerm",
        "type": "",
        "taste": "2",
        "cost": "5.39",
        "sat": "19",
        "poly": "62",
        "mono": "15",
        "other": "4",
        "total": "100",
        "nonfat": "0",
        "ratio": "8",
        "omega3": "7",
        "omega6": "55",
        "transfat": "0",
        "fridge": "y",
        "smokeC": "93",
        "smokeF": "199"
    }
];